#!/bin/sh


icon=~/.icons/dunst/memory-icon.png
title_fg="foreground='#E8E713'"
color_bg="string:bgcolor:#252732"
color_fg="string:fgcolor:#05ffaf"
time="5000"

case $BLOCK_BUTTON in
    1) notify-send  -i $icon \
                    -h $color_fg \
                    -h $color_bg  \
                    -t $time  \
    "<span $title_fg><u><b>Memory Module</b></u></span>

$(ps axch -o cmd:15,%mem --sort=-%mem | head -n 20)" ;;
esac


#free -h | awk '/^Mem:/ {print $3 "/" $2}'
#--------------------------------------------------------

TYPE="${BLOCK_INSTANCE:-mem}"

awk -v type=$TYPE '
/^MemTotal:/ {
	mem_total=$2
}
/^MemFree:/ {
	mem_free=$2
}
/^Buffers:/ {
	mem_free+=$2
}
/^Cached:/ {
	mem_free+=$2
}
/^SwapTotal:/ {
	swap_total=$2
}
/^SwapFree:/ {
	swap_free=$2
}
END {
	if (type == "swap") {
		free=swap_free/1024/1024
		used=(swap_total-swap_free)/1024/1024
		total=swap_total/1024/1024
	} else {
		free=mem_free/1024/1024
		used=(mem_total-mem_free)/1024/1024
		total=mem_total/1024/1024
	}

	pct=0
	if (total > 0) {
		pct=used/total*100
	}

	# full text   <------------- [ Option 1 ]
	#printf("%.1fG/%.1fG (%.f%%)\n", used, total, pct)

	# short text  <------------- [ Option 2 ]
	printf("%.f%%\n", pct)

	# color | if 90 then 80 70
	if (pct > 5) {
		print("#FF0000")
	} else if (pct > 6) {
		print("#FFAE00")
	} else if (pct > 7) {
		print("#FFF600")
	}
}
' /proc/meminfo
