#!/bin/sh


icon=~/.icons/dunst/ram-icon.png
title_fg="foreground='#E8E713'"
time="10000"

ALL="$(free -wh)"
TOTAL="$(free -wh | grep Mem | awk '{print $2}')"  # <------- Maybe 'add 1 to reach the correct 16G of ram'
CACHE="$(free -wh | grep Mem | awk '{print $7}')"
AVAILABLE="$(free -wh | grep Mem | awk '{print $8}')"
PERCENT_USED="$(free | grep Mem | awk '{print ($3+$5)/$2 * 100}' | sed 's/\(^..\).*/\1/')"
#PERCENT_FREE="$(free -h | grep Mem | awk '{print ($7/$2 * 100)}' | sed 's/\(^..\).*/\1/')"    <-------- About 10% off

case $BLOCK_BUTTON in
    1) notify-send  -i $icon \
                    -t $time  \
    "Memory Module

 Total....: $TOTAL
 Cache....: $CACHE
 Available: $AVAILABLE
 % Used...: $PERCENT_USED%

Top 15 Memory Hogs

$(ps axch -o cmd:25,%mem --sort=-%mem | head -n 15)
" ;;
esac


## [ Return % USED ]
## adding used + shared / total * 100 = % used | strip all but the first 2 character 
# free | grep Mem | awk '{print ($3+$5)/$2 * 100}' | sed 's/\(^..\).*/\1/'

## [ sed info ]
# s/  = substitute
# ()  = The group of two of any characters 
# ..  = starting at the beginning of the line "^" and followed by any character "." repeated zero or more times "*" (the backslashes are needed to escape some of the special characters)
# /   = the contents of the first (and only, in this case) group (here the backslash is a special escape referring to a matching sub-expression)
# /   = done
#--------------------------------------------------------
echo $PERCENT_USED%
echo $PERCENT_USED%


if [[ $PERCENT_USED -ge 80 ]]; then
    echo "#FF4848"
elif [[ $PERCENT_USED -ge 65 ]]; then
    echo "#FF9228"
elif [[ $PERCENT_USED -ge 50 ]]; then
    echo "#FFFF48"
elif [[ $PERCENT_USED -ge 40 ]]; then
    echo "#05FFAF"
else
    echo "#839496"
fi

